### ISSUE TITLE
Merge from upstream for IBM arch support

### ISSUE THREAD

**Issue by yselkowitz** [openshift/node-feature-discovery#2]
Upstream support for IBM Power LE and IBM Z architectures just landed in https://github.com/kubernetes-sigs/node-feature-discovery/pull/262.  In order to support these in OpenShift 4.2+, a merge from upstream master is needed.

**Comment by yselkowitz** [comment]
CC @crawford this is the second stage of the fix for node-feature-discovery for Power and Z.

**Comment by zvonkok** [comment]
@yselkowitz  https://github.com/openshift/node-feature-discovery/pull/4 PTAL, currently I have no access to a Power system.

**Comment by yselkowitz** [comment]
Fixed by #4, thanks.
